### ISSUE TITLE
Handling of infinity values

### ISSUE THREAD

**Issue by paxcema** [mindsdb/mindsdb_native#322]
Related issue [here](https://github.com/mindsdb/mindsdb/issues/977).

We should handle the case when a dataset has `inf` or `-inf` values, otherwise the pipeline fails further down the line. It is not immediately clear to me what the imputation should be, so I'm opening this one up for ideas and discussion.

**Comment by Winthan** [comment]
After cleaned up the data sets, data is successfully uploaded and trained.

**Comment by ZoranPandovski** [comment]
Thanks @Winthan, we should still handle those scenarios.

**Comment by George3d6** [comment]
We can convert `-inf` and `inf` to None/nan, since we handle those as inputs, handling them as outputs is out of the question, it would involve adding a separate "flag" to Numeric encoders and I think it's superflous for what is a *very* limited usecase.

Would you think that a satisfactory solution @paxcema ? It seems easy enough to implement:

1. Take df and check for inf/-inf
2. If present warn the user and convert to None
... that's about it

**Comment by paxcema** [comment]
@George3d6 yeah, I agree that sounds like a good solution
