### ISSUE TITLE
Wrong prediction value if use predict value in query

### ISSUE THREAD

**Issue by StpMax** [mindsdb/mindsdb_native#389]
It possible to use predict column in 'when_data'. If do it, then predict values will be wrong. For example, if train 'home_rentals' predictor for predict 'rental_price', and make prediction as:
```python
predictions = mdb.predict(when_data={'rental_price': '500'})
```
then predictions._data is:
```python
{'number_of_rooms': [None], 'number_of_bathrooms': [None], 'sqft': [None], 'location': [None], 'days_on_market': [None], 'initial_price': [None], 'neighborhood': [None], 'rental_price': [1046.8507351106393], '__observed_rental_price': [500], 'rental_price_confidence': [0.99], 'rental_price_confidence_range': [[1016.7710168792239, 1076.9304533420548]]}
```

**Comment by George3d6** [comment]
This is not wrong.
Youre `rental_price` value was moved to the `__observed_rental_price` column (i.e. the real value)
The `rental_price` column, much like with a normal prediction, specifies what mindsdb predicted.

This is a feature, not a bug, in that mindsdb ignores the value of the target column if you specify it during a `predict` call, and it's quite useful, since loads of times people are making predictions with test csvs that contain the target column, it would be silly to just give them back the original value instead of making a prediction.
