### ISSUE TITLE
Predictions for 'home_rentals' depend on one column

### ISSUE THREAD

**Issue by StpMax** [mindsdb/mindsdb_native#390]
* Additional info if applicable: last staging of all

I train regular 'home_rentals' predictor to predict 'rental_price' and notice my prediction depend only from one column - 'initial_price'. Not sure that a bug, because it really depend on. But should we filter such columns?
![image](https://user-images.githubusercontent.com/4068133/104700723-82c36680-570c-11eb-9afe-5afcb9161ed8.png)

**Comment by George3d6** [comment]
Not a bug, that's kind of the point of the home_rentals dataset, to see what the model does in the face of an almost-equality function (since it's not quite an equality function, rental price and initial price sometimes differ). You can always remove and/or ignore the `initial_price` column if you want to turn the dataset into a more standard regression task.
