### ISSUE TITLE
training process takes too long

### ISSUE THREAD

**Issue by ilia-tsyplenkov** [mindsdb/mindsdb_native#499]
Training process of predictor with default settings ~ 45 minutes
Training time series predictor  - more than 1.5 hours (still in progress)

**Comment by George3d6** [comment]
This is not an issue, it's expected that timeseries will take longer, i.e. much, much longer, 5-10x increased training time, depending on the data, would not surprise me. Keep in mind that for timeseries you're basically transforming `n` rows into `n x windows` rows, since `windows` row of info get appened to every row. Granted, the RNN encoder is used for that, so it's not like this scales linearly, but as a basic intuition this might help explain why it takes so long.

**Comment by ilia-tsyplenkov** [comment]
@George the original problem is that training process start to consume a lot of time. And doesn't matter what type of predictor was trained.  2 weeks ago predictor with default settings on the same datasource took me 5 mins and TS predictor only 10 mins (not 1h and 40 mins)

**Comment by paxcema** [comment]
This should be solved by #502. The problem is in the TypeDeductor phase.
