### ISSUE TITLE
Inconsistencies between the test accuracy and the confusion matrix.

### ISSUE THREAD

**Issue by George3d6** [mindsdb/mindsdb_native#69]
Given the following dataset:

[Plackett-Burman_Coffee-July.xlsx](https://github.com/mindsdb/mindsdb_native/files/4934830/Plackett-Burman_Coffee-July.xlsx)

and trying to predit: Coffe_Malt,Chocolat,Gold,Medium_Barley,Dark_Barley,Dandelion,Beets,Chicory_Roots,Figs,Dates,Cacao

There seem to be some inconsistencies between the confusion matrixes and the test accuracy (i.e. the one on the validation dataset) in scout.

Please make sure that the confusion matrix is computed on the validation dataset (the one we also use for the validation_accuracy and for the bayesian confidence models).

Barring that being an issue, please investigate if this might just boil down to an issue with scout and if so followup with @Ricram2

**Comment by Ricram2** [comment]
It seems like an issue on multiple ends. (please check on your end) 
This is one of the responses 

```
confusion_matrix: {matrix: [[4]], predicted: ["0"], real: ["0"]}
matrix: [[4]]
0: [4]
0: 4
predicted: ["0"]
0: "0"
real: ["0"]
0: "0"
```

This is what we show:

![image](https://user-images.githubusercontent.com/24927430/87736400-a4638580-c79d-11ea-95ad-e7a31df8ecff.png)

In this case, the CM is actually doing its job on expressing the result. 

On the other hand in the same analysis there's responses like:


```column_name: "Chocolat"
confusion_matrix: {matrix: [[3, 0], [0, 1]], predicted: ["0", "1"], real: ["0", "1"]}
matrix: [[3, 0], [0, 1]]
0: [3, 0]
1: [0, 1]
predicted: ["0", "1"]
0: "0"
1: "1"
real: ["0", "1"]
0: "0"
1: "1"
```

Where we show:

![image](https://user-images.githubusercontent.com/24927430/87736684-70d52b00-c79e-11ea-9ab0-304df23c3310.png)

And it is clearly not ok. see the issue here: 
https://github.com/mindsdb/mindsdb_gui/issues/476
